// src/components/NotificationContainer/index.tsx
import React from 'react';
import './style.css';
import { useSelector } from 'react-redux';
import Notification from './Notification';

const NotificationContainer = () => {
  const notifications = useSelector((state: any) => state.notifications.list);
  return (
    <div className="notification-container">
    {notifications.map((notification: any) => {
      return (
        <Notification key={notification.id} message={notification.message} time={notification.time}/>
      );
    })}
    </div>
  )
};

export default NotificationContainer;

// src/components/common/notification/NotificationContainer.vue
<template>
  <div class="notification-container">
    <div
      v-for="(notification, index) in notifications"
      :key="index"
      :class="`${notification.type} notification`"
    >
      {{notification.message}}
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex';

export default {
  computed: {
    ...mapGetters({
      notifications: 'notifications/notifications',
    }),
  },
};
</script>

<style lang="scss">
@import './notification-container-styles.scss';
</style>
